#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

##################################
### ==== SpaceVim Options ==== ###
##################################

[options]
  enable_statusline_mode = true
  enable_tabline_filetype_icon = true
  enable_os_fileformat_icon = true
  statusline_unicode_symbols = true
  statusline_separator='arrow'
  statusline_iseparator='arrow'
  autocomplete_method = 'coc'
  use_lua = 1
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  enable_guicolors = true
  buffer_index_type = 0
  enable_tabline_filetype_icon = true
  checkinstall = true
  enable_bepo_layout = false
  enable_googlesuggest = true
  enable_statusline_mode = true
  enable_statusline_tag = true
  enable_tabline_ft_icon = true
  relativenumber = false
  statusline_unicode = true
  windows_index_type = 1
  disabled_plugins = ["nerdtree"]
  bootstrap_before = 'myspacevim#before'

###############################
### ==== Native Layers ==== ###
###############################

[[layers]]
  name = 'lsp'
  enable = true
  filetypes = ['javascript', 'html', 'typescript', 'typescriptreact', 'vim', 'javascriptreact', 'css']
  enabled_clients = ['tsserver', 'typescript-language-server', 'html-languageserver', 'css-languageserver', 'vim-language-server']

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 20

[[layers]]
  name = "treesitter"

[[layers]]
  name = 'leaderf'

[[layers]]
  name = 'format'
  format_on_save = true
  enable = true

[[layers]]
  name = 'git'

[[layers]]
  name = 'cscope'

[[layers]]
  name = 'tools'

[[layers]]
  name = 'VersionControl'

[[layers]]
  name = 'core#tabline'
  enable = true

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "smart"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'incsearch'
  enable = true

[[layers]]
  name = 'foldsearch'
  enable = true

#################################
### ==== Language Layers ==== ###
#################################

[[layers]]
  name = 'lang#typescript'
  enable = true

[[layers]]
  name = 'lang#vim'
  auto_generate_doc = true

[[layers]]
  name = 'lang#toml'

[[layers]]
  name = 'lang#lua'

[[layers]]
  name = 'lang#markdown'
  enableWcwidth = 1
  listItemIndent = 1
  enabled_formater = ['prettier']

################################
### ==== Custom Plugins ==== ###
################################

[[custom_plugins]]
  repo = "lilydjwg/colorizer"
  merged = false

[[custom_plugins]]
  repo = "nvim-neo-tree/neo-tree.nvim"
  merged = false

[[custom_plugins]]
  repo = "nvim-lua/plenary.nvim"
  merged = false

[[custom_plugins]]
  repo = "kyazdani42/nvim-web-devicons"
  merged = false

[[custom_plugins]]
  repo = "MunifTanjim/nui.nvim"
  merged = false

[[custom_plugins]]
  repo = "kdheepak/lazygit.nvim"
  merged = false
